name: Deploy micro-frontends to GitHub Pages

on:
  push:
    branches: [main]            # adjust if your default branch differs
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0        # keeps Nx ‘affected’ happy

      # 2) Set up Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3) Install pnpm (v9) + enable its built-in cache
      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: |
            - args: [--frozen-lockfile, --prefer-offline]

      # 4) Build only the projects that changed (still parallel)
      - name: Build micro-frontends
        run: npm run mfe-build-all

      # 5) Collect static files for GitHub Pages
      - name: Assemble _site folder
        run: |
          set -e
          mkdir -p _site/dashboard _site/upload
          cp -r dist/apps/host/*           _site/
          cp -r dist/apps/dashboard/*      _site/dashboard/
          cp -r dist/apps/upload/*         _site/upload/

      # 6) Upload the artefact
      - uses: actions/upload-pages-artifact@v3
        with:
          name: gh-pages
          path: _site

      # 7) Publish to GitHub Pages
      - uses: actions/deploy-pages@v4
